### ISSUE TITLE
Scrolling on Android (?) mobile devices 

### ISSUE THREAD

**Issue by kprawel** [bep/gallerydeluxe#13]
Hello,

Appreciate the theme!  Unfortunately scrolling doesn't seem to work on mobile devices (I've tried a few android/chromium combos) -- other functionality works, maybe there's a configuration seeing I'm missing?

Thanks in advance!

Kyle

**Comment by Kiainigenk** [comment]
Android phones are pretty cheap 

why can't you have one :)  
Just in case for something

**Comment by bep** [comment]
>why can't you have one :)

@Kiainigenk you're right, of course. I do have some older Androids floating around, but I might as well get me a newer one and see how that feels. I'll fix this issue in a couple of days.

**Comment by kprawel** [comment]
I can confirm, the issue is now fixed, scrolling works on Android devices (tested chrome, brave, firefox, edge)
THanks!
