### ISSUE TITLE
Orientation Change

### ISSUE THREAD

**Issue by andremoreno** [bep/gallerydeluxe#3]
Hello,

Sorry I've put on a wrong repo >.<

1. Thank you for this theme.
I really like it and looks like it very simple.
just drop the new image(s) and ready...

2. I want to ask if there is anyway to fix the layout on orientation change(s)

I mean, on portrait it shows 2 photo / row
![Screenshot_20221001-140843](https://user-images.githubusercontent.com/142023/193397832-479fbe24-8e96-4af7-9c79-3d202a7e999a.png)

and when i change to landscape it shows 3 photo / row
![Screenshot_20221001-140851](https://user-images.githubusercontent.com/142023/193397838-f8d13f5b-d7a3-400a-a202-33ce96e7480e.png)

and when i change to portrait again it still showing 3 photo / row instead of 2

![Screenshot_20221001-140901](https://user-images.githubusercontent.com/142023/193397869-eda74a54-22c8-4ab4-9280-67463911a119.png)

3. Exif
(dont know if i have to ask in here or better to open a new issue)
Is there a good way to show the exif ?

I've try on my repo https://github.com/andremoreno/a7gallery 
i'm try to add the exif to json via init.html 

Thank you ..

**Comment by bep** [comment]
>I really like it and looks like it very simple.

Thanks for the kind words.

I have pushed a fix for the orientation bug.

As to Exif, see #4 -- I'm struggling a little with where to put that exif info; it looks fine on larger screens, but not so on mobile. Suggestion welcome.
