### ISSUE TITLE
Struggling with deployment (newbie)

### ISSUE THREAD

**Issue by Krap1v** [bep/gallerydeluxe#5]
Hey Bep. Loving the theme and Hugo so far.
Im just started to learn Hugo and i have been struggling to deploy this theme locally for the past day. (Read the Hugo documentation, but no luck)
Would be awesome If you could add some manual how to deploy this properly (for noobs like me).
Thank you!

**Comment by bep** [comment]
Yea, I will try to improve on this, but the main thing to understand is that in most cases you don't to just copy the exampleSite folder and start from that.

**Comment by bep** [comment]
See https://github.com/bep/gallerydeluxe_starter
